site_name: pyprojectsort
docs_dir: .
site_url: https://kieran-ryan.github.io/pyprojectsort
theme:
  name: material
  palette:
    scheme: slate

  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/kieran-ryan/pyprojectsort

plugins:
  - same-dir
