name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Build and publish Python 🐍 distributions 📦 to ${{ matrix.environment.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - name: testpypi
            url: https://test.pypi.org/project/pyprojectsort
            token: TEST_PYPI_API_TOKEN
            repository-url: https://test.pypi.org/legacy/
          - name: pypi
            url: https://pypi.org/project/pyprojectsort
            token: PYPI_API_TOKEN
            repository-url: https://upload.pypi.org/legacy/
    environment:
      name: ${{ matrix.environment.name }}
      url: ${{ matrix.environment.url }}
    permissions:
      id-token: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - name: Build package
        run: make build
      - name: Publish distribution 📦 to ${{ matrix.environment.name }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets[matrix.environment.token] }}
          repository-url: ${{ matrix.environment.repository-url }}

  deploy-docs:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    name: Build docs with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
      - name: Build docs
        run: make docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true
